
version: "2"
services:
  backup:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # AWS Configuration
      ## All fields are mandatory
      - AWS_BACKUP_BUCKET=muretech-fna-backup
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      # Database Configuration
      ## MYSQL_DATABASE - is optional, in case this parameter is not provided,
      ## it will backup all databases
      ## MYSQL_PORT - is optional, default 3306
      - MYSQL_DATABASE=fna-docgen-db
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=root_pass

      # Add this field if you want to roolback database from a backup
      # You could provide a date (YYYY-MM-DDTHH-mm) to select a backup 
      # or 'latest' to select the latest backup
      - ROLLBACK=latest

  db:
    image: mysql:8
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=fna-docgen-db
    security_opt:
      - seccomp:unconfined
    volumes:
      - data-mysql:/var/lib/mysql

volumes:
  data-mysql: